In [2]:
import torch

In [3]:
a = torch.tensor([1, 2, 3], dtype=torch.float32)
b = torch.tensor([4, 5, 6], dtype=torch.float32)
c = torch.tensor([7, 8, 9], dtype=torch.float32)
t = torch.stack([a, b, c])
t = t.unsqueeze(1)

In [9]:
a = torch.tensor([[1,2,3], [4,5,6]], dtype=torch.float32)
b = torch.tensor([[7,8,9], [10,11,12]], dtype=torch.float32)
t = torch.stack([a, b], dim=0)
print(t)

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])


In [10]:
print(t.shape)
print(t)

torch.Size([3, 1, 3])
tensor([[[1., 2., 3.]],

        [[4., 5., 6.]],

        [[7., 8., 9.]]])


In [ ]:
print()

In [11]:
output_mean = torch.mean(t, dim=0)

In [12]:
print(output_mean)

tensor([[4., 5., 6.]])


In [13]:
print(output_mean.shape)

torch.Size([1, 3])


In [15]:
a = torch.rand((2,336,512), dtype=torch.float32)
print(a.shape)
a_mean = a.mean(dim=1)
print(a_mean.shape)

torch.Size([2, 336, 512])
torch.Size([2, 512])
