In [1]:
import torch


In [2]:
a = torch.tensor([1,2,3], dtype=torch.float32)
b = torch.tensor([4,5,6], dtype=torch.float32)
a = a.view(3,1)
b = b.view(3,1)
print(a)
print(b)

tensor([[1.],
        [2.],
        [3.]])
tensor([[4.],
        [5.],
        [6.]])


In [3]:
torch.cat((a,b), dim=1)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])