In [1]:
import torch

In [24]:
a = torch.tensor([1, 2, 3], dtype=torch.float32)
b = torch.tensor([4, 5, 6], dtype=torch.float32)
c = torch.tensor([7, 8, 9], dtype=torch.float32)
t = torch.stack([a, b, c])
t = t.unsqueeze(1)
print(t.shape)

torch.Size([3, 1, 3])


In [25]:
t_min = t.min(axis=2, keepdim=True)[0]
t_max = t.max(axis=2, keepdim=True)[0]
t = (t - t_min) / (t_max - t_min)
print(t)

tensor([[[0.0000, 0.5000, 1.0000]],

        [[0.0000, 0.5000, 1.0000]],

        [[0.0000, 0.5000, 1.0000]]])


In [6]:
a = torch.tensor([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ],
    [
        [13,14,15],
        [16,17,18]
    ],
    [
        [19,20,21],
        [22,23,24]
    ]
])
print(a.shape)
a = a.transpose(1, 2)
print(a)


torch.Size([4, 2, 3])
tensor([[[ 1,  4],
         [ 2,  5],
         [ 3,  6]],

        [[ 7, 10],
         [ 8, 11],
         [ 9, 12]],

        [[13, 16],
         [14, 17],
         [15, 18]],

        [[19, 22],
         [20, 23],
         [21, 24]]])


In [9]:
a = torch.tensor([[1,2,3], [4,5,6]], dtype=torch.float32)
b = torch.tensor([[7,8,9], [10,11,12]], dtype=torch.float32)
t = torch.stack([a, b], dim=0)
print(t)

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])
